"""
train_yolov8n_night_v2.py — Phase.116 §11.47.13 fine-tune yolov8n on
ROBOFLOW-LABELED night corpus.

This is the v2 training script. The original train_yolov8n_night.py was
written for ExDark + pseudo-labeling; v2 is focused on the manual-labeling
path (Roboflow → YOLO format → fine-tune).

Pre-requisites (do these first, before running this script):
  1. .venv/bin/python scripts/extract_night_training_candidates.py --days 30
  2. Upload candidates/ to Roboflow, label bounding boxes for real vehicles/
     people/animals (ignore noise — trees, reflections, edge artifacts)
  3. Export as YOLOv8 format, download zip
  4. Unzip into data/training_corpus/yolov8n_night/labeled/

Usage:
    .venv/bin/python scripts/train_yolov8n_night_v2.py [--epochs 50] [--batch 8]

Outputs:
    runs/detect/train/             — ultralytics training artifacts
    models/yolov8n-night.onnx      — final exported model (gitignored)
    docs/NIGHT-MODEL-<timestamp>.md — run log with metrics + validation

Why this is needed:
    §11.47.12 showed the heuristic gate keeps yolov8n+heuristic at 1.25% FP rate
    on night frames. But it doesn't actually FIND real night vehicles — it only
    rejects the obvious noise. A yolov8n fine-tuned on real IR night data would
    produce fewer FPs AND catch more true positives. That's the goal of this
    script. Threshold: if val mAP@0.5 > 0.6 and night-frame recall > 0.7, ship.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))


LABELED_DIR = _ROOT / "data" / "training_corpus" / "yolov8n_night" / "labeled"
MODEL_OUT = _ROOT / "models" / "yolov8n-night.onnx"
DOCS_DIR = _ROOT / "docs"
WEIGHTS = _ROOT / "models" / "yolov8n.pt"  # ultralytics needs .pt for training


def check_prerequisites() -> tuple[bool, str]:
    """Verify the labeled corpus exists and ultralytics is installed."""
    if not LABELED_DIR.is_dir():
        return False, f"Missing: {LABELED_DIR}. Run extraction + Roboflow labeling first."
    images_dir = LABELED_DIR / "images"
    labels_dir = LABELED_DIR / "labels"
    if not images_dir.is_dir() or not labels_dir.is_dir():
        return False, f"{LABELED_DIR} missing images/ or labels/ subdirectory (expected Roboflow YOLOv8 format)."
    n_images = sum(1 for _ in images_dir.glob("*.jpg")) + sum(1 for _ in images_dir.glob("*.png"))
    n_labels = sum(1 for _ in labels_dir.glob("*.txt"))
    if n_images == 0:
        return False, f"No images found in {images_dir}"
    if n_labels == 0:
        return False, f"No label files found in {labels_dir}"
    return True, f"{n_images} images, {n_labels} labels"


def write_dataset_yaml() -> Path:
    """Write ultralytics dataset.yaml pointing at our labeled corpus."""
    yaml_path = LABELED_DIR / "dataset.yaml"
    content = (
        f"# Auto-generated by train_yolov8n_night_v2.py\n"
        f"path: {LABELED_DIR}\n"
        f"train: images\n"
        f"val: images\n"  # ultralytics will auto-split if no val/ dir
        f"\n"
        f"# COCO 80 classes (yolov8n pretrained on COCO)\n"
        f"names:\n"
        f"  0: person\n"
        f"  1: bicycle\n"
        f"  2: car\n"
        f"  3: motorcycle\n"
        f"  4: airplane\n"
        f"  5: bus\n"
        f"  6: train\n"
        f"  7: truck\n"
        f"  8: boat\n"
        f"  9: traffic light\n"
        f"  10: fire hydrant\n"
        f"  11: stop sign\n"
        f"  12: parking meter\n"
        f"  13: bench\n"
        f"  14: bird\n"
        f"  15: cat\n"
        f"  16: dog\n"
        f"  17: horse\n"
        f"  18: sheep\n"
        f"  19: cow\n"
        f"  20: elephant\n"
        f"  21: bear\n"
        f"  22: zebra\n"
        f"  23: giraffe\n"
        f"  24: backpack\n"
    )
    yaml_path.write_text(content)
    return yaml_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=50)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--device", default="mps", help="mps, cpu, or cuda:0")
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--patience", type=int, default=10,
                    help="Early stopping patience (epochs without improvement)")
    args = ap.parse_args()

    # Prerequisites
    ok, msg = check_prerequisites()
    if not ok:
        print(f"[train] BLOCKED: {msg}")
        return 1
    print(f"[train] Prerequisites OK: {msg}")

    # Lazy import ultralytics so the script can be inspected without torch installed
    try:
        from ultralytics import YOLO
    except ImportError:
        print("[train] ultralytics not installed. Run: .venv/bin/pip install ultralytics")
        return 1

    if not WEIGHTS.is_file():
        print(f"[train] Downloading yolov8n.pt to {WEIGHTS}...")
        YOLO("yolov8n.pt")  # ultralytics auto-downloads to cwd, then we move
        cwd_pt = Path("yolov8n.pt").resolve()
        if cwd_pt.is_file():
            shutil.move(str(cwd_pt), str(WEIGHTS))

    yaml_path = write_dataset_yaml()
    print(f"[train] Dataset yaml: {yaml_path}")

    print(f"[train] Loading {WEIGHTS}...")
    model = YOLO(str(WEIGHTS))

    print(f"[train] Starting training: epochs={args.epochs}, batch={args.batch}, device={args.device}...")
    t0 = time.time()
    results = model.train(
        data=str(yaml_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        patience=args.patience,
        project=str(_ROOT / "runs" / "detect"),
        name="train",
        exist_ok=True,
        # Augmentation tuned for IR/low-light
        hsv_h=0.0,  # hue shifts break IR monochrome
        hsv_s=0.3,  # some saturation variation
        hsv_v=0.5,  # brightness jitter — important for night
        degrees=5.0,
        translate=0.1,
        scale=0.3,
        fliplr=0.5,
        mosaic=1.0,
    )
    train_seconds = time.time() - t0
    print(f"[train] Training done in {train_seconds/60:.1f} minutes")

    # Export best.pt to ONNX
    best_pt = Path(results.save_dir) / "weights" / "best.pt"
    if not best_pt.is_file():
        print(f"[train] ERROR: best.pt not found at {best_pt}")
        return 1
    print(f"[train] Loading best.pt for export: {best_pt}")
    best_model = YOLO(str(best_pt))
    print(f"[train] Exporting to {MODEL_OUT}...")
    best_model.export(format="onnx", imgsz=args.imgsz, simplify=True)
    # ultralytics exports next to source; move to MODEL_OUT
    exported = best_pt.with_suffix(".onnx")
    if exported.is_file() and not MODEL_OUT.exists():
        shutil.move(str(exported), str(MODEL_OUT))

    print(f"[train] ONNX model: {MODEL_OUT}")

    # Write run log
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    log_path = DOCS_DIR / f"NIGHT-MODEL-{timestamp}.md"
    log_content = (
        f"# Night Model Training Run — {timestamp}\n\n"
        f"- **Epochs**: {args.epochs}\n"
        f"- **Batch**: {args.batch}\n"
        f"- **Device**: {args.device}\n"
        f"- **Image size**: {args.imgsz}\n"
        f"- **Training time**: {train_seconds/60:.1f} minutes\n"
        f"- **Source corpus**: {msg}\n"
        f"- **Output model**: `{MODEL_OUT}`\n\n"
        f" Next steps\n\n"
        f"1. Validate against held-out 50 native night frames using probe_night_reflections.py\n"
        f"2. If FP rate < current (1.25%) AND real detection rate maintained, ship behind\n"
        f"   `MOTION_GATE_NIGHT_MODEL_PATH=models/yolov8n-night.onnx` env var\n"
        f"3. If regression, keep current yolov8n+heuristic as default\n"
    )
    log_path.write_text(log_content)
    print(f"[train] Run log: {log_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())